launcher_version=1.0.6
java_version=21

releases_repository=blazexpsn/Minecraft-ABNW
releases_branch=main
launcher_repository=blazexpsn/ABNW-Launcher
launcher_branch=main
msa_client_id=c36a9fb6-4f2a-41ff-90bd-ae7cc92031eb
discord_client_id=1549348591179534346
cosmetics_api_url=https://abnw-cosmetics.blazexpsn.workers.dev
patreon_page_url=

shadow_version=9.4.3
imgui_version=1.92.7.1
lwjgl_version=3.4.1
gson_version=2.13.2
vcdiff_version=0.1.1
slf4j_version=2.0.17
