version=${version}
repository=${repository}
branch=${branch}
launcherRepository=${launcherRepository}
launcherBranch=${launcherBranch}
msaClientId=${msaClientId}
msaLauncherClientId=${msaLauncherClientId}
discordClientId=${discordClientId}
cosmeticsApiUrl=${cosmeticsApiUrl}
patreonPageUrl=${patreonPageUrl}
